name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  lint-and-test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --shamefully-hoist=true
      - run: pnpm build
      - run: pnpm test
